# Generated by Django 4.0.4 on 2022-04-29 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACCEPTED', 'Accepted'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=128)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('LOCAL', 'Local'), ('REGION', 'Region'), ('RUSSIA', 'Russia'), ('WORLD', 'World'), ('ONLINE', 'Online')], default='LOCAL', max_length=128)),
                ('format', models.CharField(choices=[('PAIR', 'Pair'), ('TEAM', 'Team'), ('INDIVIDDUAL', 'Individdual')], default='PAIR', max_length=128)),
                ('editors', models.ManyToManyField(related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
            },
        ),
    ]
