# Generated by Django 4.0.4 on 2022-04-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACCEPTED', 'Accepted'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=128)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('LOCAL', 'Local'), ('REGION', 'Region'), ('RUSSIA', 'Russia'), ('WORLD', 'World'), ('ONLINE', 'Online')], max_length=128)),
                ('format', models.CharField(choices=[('PAIR', 'Pair'), ('TEAM', 'Team'), ('INDIVIDDUAL', 'Individual')], max_length=128)),
            ],
        ),
    ]
