# Generated by Django 4.0.4 on 2022-04-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
