# Generated by Django 4.0.4 on 2022-04-27 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_tournament_is_cancelled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='editors',
            field=models.ManyToManyField(related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
