# Generated by Django 4.0.4 on 2022-04-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_tournament_options_tournament_editors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_cancelled',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('PAIR', 'Pair'), ('TEAM', 'Team'), ('INDIVIDDUAL', 'Individdual')], default='PAIR', max_length=128),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('REGION', 'Region'), ('RUSSIA', 'Russia'), ('WORLD', 'World'), ('ONLINE', 'Online')], default='LOCAL', max_length=128),
        ),
    ]
